'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Check,Database,FileSpreadsheet,FolderOpen,Link2,RefreshCw,ShieldCheck,X} from 'lucide-react';
import {pickSpreadsheet} from '@/lib/google-picker';
type Id='supabase_calls'|'supabase_crm'|'google';
type Item={id:Id;ready:boolean;authorized:boolean;selected:Record<string,string>;error:string};
type Project={id:string;name:string;region:string;status:string};
const names:Record<Id,string>={supabase_calls:'Call logs & attribution',supabase_crm:'CRM customers & payments',google:'Website click spreadsheet'};
export default function Connections(){
 const [items,setItems]=useState<Item[]>([]),[primary,setPrimary]=useState(''),[pickerReady,setPickerReady]=useState(false),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[chooser,setChooser]=useState<Id|null>(null),[projects,setProjects]=useState<Project[]>([]),[selection,setSelection]=useState('');
 async function api(path:string,method='GET',body?:unknown){const response=await fetch('/api/integrations'+path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(response.status===401){window.location.assign('/login');throw new Error('Sign in required.');}const data=await response.json();if(!response.ok)throw new Error(data.error||'Connection failed.');return data;}
 async function refresh(){try{const data=await api('');setItems(data.items);setPrimary(data.primaryRef);setPickerReady(data.pickerReady);}catch(error){setNotice(error instanceof Error?error.message:'Connection check failed.');}}
 useEffect(()=>{refresh();const params=new URLSearchParams(window.location.search);if(params.get('error'))setNotice(params.get('error')!);else if(params.has('connected'))setNotice('Account authorized.');window.history.replaceState({},'',window.location.pathname);},[]);
 async function run(id:string,action:()=>Promise<void>){setBusy(id);setNotice('');try{await action();}catch(error){setNotice(error instanceof Error?error.message:'Connection failed.');}finally{setBusy('');}}
 function connect(id:Id){run(id,async()=>{const data=await api('/'+id+'/start','POST');window.location.assign(data.url);});}
 function chooseProject(id:Id){run(id,async()=>{const data=await api('/'+id+'/projects');setProjects(data.projects);setSelection('');setChooser(id);});}
 function saveProject(){if(!chooser||!selection)return;run(chooser,async()=>{await api('/'+chooser+'/select','POST',{project_ref:selection});setChooser(null);await refresh();setNotice('Database connection verified and saved.');});}
 function chooseSheet(){run('google',async()=>{const config=await api('/google/picker','POST');const fileId=await pickSpreadsheet(config);if(!fileId)return;const saved=await api('/google/sheet','POST',{fileId});await refresh();setNotice('Selected '+saved.name+'.');});}
 function disconnect(id:Id){if(!window.confirm('Remove this saved connection? Existing call records and CRM data will not be deleted.'))return;run(id,async()=>{await api('/'+id+'/disconnect','POST');await refresh();setNotice('Saved authorization removed. Existing data is unchanged.');});}
 return <div className="setup-page"><header className="setup-header"><a href="/" className="secondary"><ArrowLeft size={16}/>Dashboard</a><strong>GSMWeb</strong><span className="demo-tag">CONNECTIONS</span></header><main className="setup-main"><div className="section-heading"><div><div className="eyebrow">WORKSPACE SETTINGS</div><h1>Connections</h1></div><button className="secondary" disabled={Boolean(busy)} onClick={refresh}><RefreshCw size={16}/>Refresh</button></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={16}/></button></div>}
 <div className="setup-list">{(['supabase_calls','supabase_crm','google'] as const).map(id=>{const item=items.find(x=>x.id===id),selected=id==='google'?item?.selected.sheet_name:item?.selected.name;return <section className="setup-provider" key={id}><div className="setup-provider-title"><span className="setup-provider-icon">{id==='google'?<FileSpreadsheet size={24}/>:<Database size={24}/>}</span><div><small>{id==='google'?'Google Drive':'Supabase'}</small><h2>{names[id]}</h2></div><span className={'badge '+(selected?'confirmed':'unmatched')}>{selected?'Selected':item?.authorized?'Account authorized':item?.ready?'Not connected':'Registration pending'}</span></div><div className="setup-selection"><span className="muted">{id==='google'?'Spreadsheet':'Database'}</span><strong>{selected||(id==='supabase_calls'?primary:'Not selected')}</strong>{id!=='google'&&item?.selected.project_ref&&<small>{item.selected.project_ref}</small>}</div>{item?.error&&<p role="alert">{item.error}</p>}<div className="setup-actions"><button className="primary" disabled={!item?.ready||Boolean(busy)} onClick={()=>connect(id)}><Link2 size={16}/>{item?.authorized?'Reconnect account':id==='google'?'Connect Google Drive':'Connect Supabase'}</button>{item?.authorized&&(id==='google'?<button className="secondary" disabled={!pickerReady||Boolean(busy)} onClick={chooseSheet}><FolderOpen size={16}/>Choose spreadsheet</button>:<button className="secondary" disabled={Boolean(busy)} onClick={()=>chooseProject(id)}><Database size={16}/>Choose project</button>)}{item?.authorized&&<button className="secondary" disabled={Boolean(busy)} onClick={()=>disconnect(id)}><X size={16}/>Disconnect</button>}</div></section>;})}</div><footer><ShieldCheck size={16}/>Administrator access<span>Encrypted server-side connections</span></footer></main>
 {chooser&&<div className="modal-backdrop" onClick={()=>setChooser(null)}><section className="modal setup-modal" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2>Select Supabase project</h2><button className="icon-btn" onClick={()=>setChooser(null)} aria-label="Close"><X/></button></div><fieldset><legend>{names[chooser]}</legend>{projects.map(project=>{const available=chooser!=='supabase_calls'||project.id===primary;return <label key={project.id} className={'candidate-option '+(!available?'disabled-project':'')}><input type="radio" name="project" disabled={!available||project.status!=='ACTIVE_HEALTHY'} checked={selection===project.id} onChange={()=>setSelection(project.id)}/><div><b>{project.name}</b><small>{project.id} · {project.region}</small>{!available&&<small>Different authentication database</small>}</div></label>;})}{projects.length===0&&<p>No projects available to this account.</p>}</fieldset><div className="modal-actions"><button className="secondary" onClick={()=>setChooser(null)}>Cancel</button><button className="primary" disabled={!selection||Boolean(busy)} onClick={saveProject}><Check size={16}/>Use project</button></div></section></div>}</div>;
}
